version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: mysql_container
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD = ${MYSQLDB_ROOT_PASSWORD}
      - MYSQL_DATABASE = ${MYSQLDB_DATABASE}
      - MYSQL_USER = ${MYSQLDB_USER}
      - MYSQL_PASSWORD = ${MYSQLDB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
volumes:
  mysql_data: